### ISSUE TITLE
How to set up the .env file?  Do you have an example?

### ISSUE THREAD

**Issue by GStuD2** [penn201500/tron-wallet-generator-and-transfer#1]
It's a nice project for Tron wallet actions. But I'm trying to figure out how to use retrieveFunds.js with the correct args. How can I set up the .env file?

```javascript
 const tronGridEndpoint = `${process.env.TRONSCAN_QUERY_API}${txid}`
  try {
    const response = await axios.get(tronGridEndpoint, {
      headers: {
        Accept: "application/json, text/plain, */*",
        "TRON-PRO-API-KEY": process.env.TRONGRID_API_KEY,
      },
    })
```

**Comment by penn201500** [comment]
Here is an example:

```bash
TRON_FULL_HOST=https://api.shasta.trongrid.io
TRONSCAN_QUERY_API=https://shastapi.tronscan.org/api/transaction-info?hash=
SENDER_PRIVATE_KEY=59604d0b4e598dccc2ab82bab689bxxxxxxxxxxxxxx
TRONGRID_API_KEY=25f66928-0b70-48cd-9ac6-da6f8247c663
```
The network of mainnet and testnet, you can check the details here: https://developers.tron.network/reference/background

As to the API key, you can read this: https://developers.tron.network/reference/select-network
And https://www.trongrid.io/
