### ISSUE TITLE
This isn't an issue 

### ISSUE THREAD

**Issue by Baatinarolu** [penn201500/tron-wallet-generator-and-transfer#2]
The wallet generated with wallet acc is it from, id it trust wallet, binance or which one

**Comment by penn201500** [comment]
I didn't get your meaning. I guess you missed the README

**Comment by Baatinarolu** [comment]
I mean what wallet will we use to import the phrase seed, because there is
alot of wallet application

**Comment by penn201500** [comment]
Tron, you can check it here: https://tronscan.org/#/

**Comment by Baatinarolu** [comment]
Thanks, I'll check it out!
